 const availableItems = {
    one: {
        id: 1,
        name: "Training Sword",
        description: "Practice item. Confers no benefit.",
        strength: 0,
        str_gear_num: 0,
        str_class_bonus: 0,
        constitution: 0,
        const_gear_num: 0,
        const_class_bonus: 0,
        intelligence: 0,
        int_gear_num: 0,
        int_class_bonus: 0,
        perception: 0,
        perc_gear_num: 0,
        perc_class_bonus: 0,
        cost: 1,
        image: "https://habitica-assets.s3.amazonaws.com/mobileApp/images/shop_weapon_warrior_0.png"
    },
    two: {
        id: 2,
        name: "Leather Armor",
        description: "Jerkin of sturdy boiled hide. \n Increases Constitution by 3.",
        strength: 0,
        str_gear_num: 0,
        str_class_bonus: 0,
        constitution: 0,
        const_gear_num: 0,
        const_class_bonus: 0,
        intelligence: 0,
        int_gear_num: 0,
        int_class_bonus: 0,
        perception: 0,
        perc_gear_num: 0,
        perc_class_bonus: 0,
        cost: 1,
        image: "https://habitica-assets.s3.amazonaws.com/mobileApp/images/shop_armor_warrior_1.png"
    },
    three: {
        id: 3,
        name: "Wooden Shield",
        description: "Round shield of thick wood. Increases Constitution by 2.",
        strength: 0,
        str_gear_num: 0,
        str_class_bonus: 0,
        constitution: 3,
        const_gear_num: 2,
        const_class_bonus: 1,
        intelligence: 0,
        int_gear_num: 0,
        int_class_bonus: 0,
        perception: 0,
        perc_gear_num: 0,
        perc_class_bonus: 0,
        cost: 20,
        image: "https://habitica-assets.s3.amazonaws.com/mobileApp/images/shop_shield_warrior_1.png"

    },
    four: {
        id: 4,
        name: "Leather Helm",
        description: "Cap of sturdy boiled hide. Increases Strength by 2.",
        strength: 3,
        str_gear_num: 2,
        str_class_bonus: 1,
        constitution: 0,
        const_gear_num: 0,
        const_class_bonus: 0,
        intelligence: 0,
        int_gear_num: 0,
        int_class_bonus: 0,
        perception: 0,
        perc_gear_num: 0,
        perc_class_bonus: 0,
        cost: 15,
        image: "https://habitica-assets.s3.amazonaws.com/mobileApp/images/shop_head_warrior_1.png"
    },
    five: {
        id: 5,
        name: "Health Potion",
        description: "Recover 15 health. (Instant Use)",
        strength: 0,
        str_gear_num: 0,
        str_class_bonus: 0,
        constitution: 0,
        const_gear_num: 0,
        const_class_bonus: 0,
        intelligence: 0,
        int_gear_num: 0,
        int_class_bonus: 0,
        perception: 0,
        perc_gear_num: 0,
        perc_class_bonus: 0,
        cost: 25,
        image: "https://habitica-assets.s3.amazonaws.com/mobileApp/images/shop_potion.png"
    },
    six: {
        id: 6,
        name: "Enchanted Armoire",
        description: "Open the armoire to randomly receive special Equipment, Experience, or Food!",
        strength: 0,
        str_gear_num: 0,
        str_class_bonus: 0,
        constitution: 0,
        const_gear_num: 0,
        const_class_bonus: 0,
        intelligence: 0,
        int_gear_num: 0,
        int_class_bonus: 0,
        perception: 0,
        perc_gear_num: 0,
        perc_class_bonus: 0,
        cost: 100,
        image: "https://habitica-assets.s3.amazonaws.com/mobileApp/images/shop_armoire.png"

    }
}

export default availableItems;
